- name: Configure EC2 instances
  hosts: ec2  # Replace 'ec2' with your actual inventory group name if different
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
